//! Types for the long-term memory bridge.
//!
//! Phase 7 implementation.

#![allow(dead_code)]

use serde::{Deserialize, Serialize};

/// Result of flushing beliefs to long-term storage.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FlushResult {
    pub beliefs_written: usize,
    pub causal_edges_written: usize,
    pub duration_ms: u64,
}

/// Schema descriptor for a `BeliefQuad` domain.
///
/// Generated by `#[derive(BeliefState)]` (Phase 4) and passed to `load()` to
/// reconstruct a typed quad from long-term storage.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SchemaDescriptor {
    pub domain: String,
    pub belief_keys: Vec<BeliefKeyDescriptor>,
    pub version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BeliefKeyDescriptor {
    pub key: String,
    pub value_type: String,
    pub source: String,
    pub has_ttl: bool,
    pub has_prospective_index: bool,
}
